"""add retrieved_chunks association table

Revision ID: 7b774bea7f0b
Revises: 7f3330f751fe
Create Date: 2026-09-30 15:43:59.243202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b774bea7f0b'
down_revision: Union[str, Sequence[str], None] = '7f3330f751fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retrieved_chunks',
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['queries.query_id'], ),
    sa.PrimaryKeyConstraint('query_id', 'chunk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retrieved_chunks')
    # ### end Alembic commands ###
